const WEATHER_REQUEST_RECEIVED = 'WEATHER_REQUEST_RECEIVED';
const WEATHER_REQUEST_ERROR = 'WEATHER_REQUEST_ERROR';
const WEATHER_DATA_RECEIVED = 'WEATHER_DATA_RECEIVED';
const WEATHER_DATA_UPDATE = 'WEATHER_DATA_UPDATE';
const WEATHER_ZIPCODE_CHANGED = 'WEATHER_ZIPCODE_CHANGED';

const STOCK_REQUEST_RECEIVED = 'STOCK_REQUEST_RECEIVED';
const STOCK_REQUEST_ERROR = 'STOCK_REQUEST_ERROR';
const STOCK_DATA_RECEIVED = 'STOCK_DATA_RECEIVED';
const STOCK_DATA_UPDATE = 'STOCK_DATA_UPDATE';

const LOGGING_IN_DEVICE = 'LOGGING_IN_DEVICE';
const ERROR_LOGGING_IN = 'ERROR_LOGGING_IN';
const LOGGED_IN = 'LOGGED_IN';

module.exports = {
  WEATHER_REQUEST_RECEIVED,
  WEATHER_REQUEST_ERROR,
  WEATHER_DATA_RECEIVED,
  WEATHER_DATA_UPDATE,
  WEATHER_ZIPCODE_CHANGED,
  STOCK_REQUEST_RECEIVED,
  STOCK_REQUEST_ERROR,
  STOCK_DATA_RECEIVED,
  STOCK_DATA_UPDATE,
  LOGGING_IN_DEVICE,
  ERROR_LOGGING_IN,
  LOGGED_IN,
};
