// WEATHER

const START_WEATHER_POLLING = 'START_WEATHER_POLLING';
const STOP_WEATHER_POLLING = 'STOP_WEATHER_POLLING';
const WEATHER_POLLING_STOPPED = 'WEATHER_POLLING_STOPPED';
const WEATHER_DATA_RECEIVED = 'WEATHER_DATA_RECEIVED';
const WEATHER_REQUEST_ERROR = 'WEATHER_REQUEST_ERROR';
const WEATHER_DATA_UPDATE = 'WEATHER_DATA_UPDATE';
const SAVE_WEATHER_CONFIG = 'SAVE_WEATHER_CONFIG';
const WEATHER_CONFIG_SAVED = 'WEATHER_CONFIG_SAVED';
const WEATHER_CONFIG_SAVE_ERROR = 'WEATHER_CONFIG_SAVE_ERROR';

// STOCKS

const START_STOCK_POLLING = 'START_STOCK_POLLING';
const STOP_STOCK_POLLING = 'STOP_STOCK_POLLING';
const STOCK_POLLING_STOPPED = 'STOCK_POLLING_STOPPED';

const STOCK_REQUEST_RECEIVED = 'STOCK_REQUEST_RECEIVED';
const STOCK_REQUEST_ERROR = 'STOCK_REQUEST_ERROR';
const STOCK_DATA_RECEIVED = 'STOCK_DATA_RECEIVED';
const STOCK_DATA_UPDATE = 'STOCK_DATA_UPDATE';
const STOCK_SYMBOL_ADDED = 'STOCK_SYMBOL_ADDED';

// DEVICE

const LOGGING_IN_DEVICE = 'LOGGING_IN_DEVICE';
const ERROR_LOGGING_IN = 'ERROR_LOGGING_IN';
const LOGGED_IN = 'LOGGED_IN';

module.exports = {
  START_WEATHER_POLLING,
  STOP_WEATHER_POLLING,
  WEATHER_POLLING_STOPPED,
  WEATHER_DATA_RECEIVED,
  WEATHER_REQUEST_ERROR,
  WEATHER_DATA_UPDATE,
  SAVE_WEATHER_CONFIG,
  WEATHER_CONFIG_SAVED,
  WEATHER_CONFIG_SAVE_ERROR,


  START_STOCK_POLLING,
  STOP_STOCK_POLLING,
  STOCK_POLLING_STOPPED,
  STOCK_REQUEST_RECEIVED,
  STOCK_REQUEST_ERROR,
  STOCK_DATA_RECEIVED,
  STOCK_DATA_UPDATE,
  STOCK_SYMBOL_ADDED,

  LOGGING_IN_DEVICE,
  ERROR_LOGGING_IN,
  LOGGED_IN,
};
